### PR TITLE
Add SBOL types to the OM and PROV classes

### LINKED ISSUE #28: SBOL 3 measurement and provenance examples lack a second SBOL rdf type
Measurement entities should have two rdf:type properties, one in the om: namespace and another in the sbol: namespace. The sample files in the `measurement_entity` directory lack the second rdf:type property from the sbol: namespace.

@cjmyers @jakebeal am I correct that measurement and provenance entities should all have a second rdf:type property in the sbol: namespace if they are expected to be validated as SBOL entities?

### PR DESCRIPTION
**Pull request by tcmitchell**
All non-SBOL types that make use of properties in the SBOL namespace
should have two RDF types, one outside the SBOL namespace and one
inside the SBOL namespace. The measurement and provenance examples only had the RDF
type that was outside the SBOL namespace, while using properties
within the SBOL namespace like http://sbols.org/v3#displayId and
http://sbols.org/v3#name.

Closes #28

### CODE REVIEW

**Comment by tcmitchell** [comment]
@goksel @udp @cjmyers @jakebeal 

I'd like to get others to look at this to see if you agree or disagree with this interpretation of the spec.

**Comment by cjmyers** [comment]
I agree that they should have this extra namespace to be validated by the SBOL validator.  It is not, however, illegal to be missing the SBOL namespace, it would just not be validated by the SBOL validator.

**Comment by jakebeal** [comment]
To be precise, because RDF is open-world, we cannot control somebody's ability to use an SBOL term in a non-SBOL document.  That said, I think that it will generally be more likely for type information to be missing because somebody has an error in an SBOL document rather than that they are intentionally using SBOL terms outside of SBOL. 

As such, I believe that it would be appropriate to say that SBOL terms SHOULD NOT be used without accompanying SBOL type information, and it would be useful to have an SBOL library warn if it detects any loose SBOL terms in other parts of the graph (if this is not too expensive).

We should probably add a line to the spec to clarify.

**Comment by tcmitchell** [comment]
This was discussed on the October 21, 2020 SBOL 3 call and there were no objections to merging.

**Pull request merged**
